networks:
  hadoop-net:
    driver: bridge

services:
  client:
    image: client
    container_name: client
    hostname: quochuy-client
    ports:
      - "4040:4040"
    volumes:
      - ./data:/home/hadoopquochuy/data


    networks:
      - hadoop-net
    command: /bin/bash -c "service ssh start; tail -f /dev/null"

  master:
    image: master-official
    container_name: master
    hostname: quochuy-master
    volumes:
      - hdfs_namenode:/home/hadoopquochuy/hadoop/hadoop_data/hdfs/namenode
      - ./scripts:/home/hadoopquochuy/scripts

    ports:
      - "9004:9004"
      - "9870:9870"

    networks:
      - hadoop-net
    command: /bin/bash -c "service ssh start; tail -f /dev/null"
    
volumes:
  hdfs_namenode:
