networks:
  hadoop-net:
    driver: bridge

services:
  client:
    build:
      context: ../
      dockerfile: docker/client.dockerfile
    image: client
    container_name: client
    hostname: client-server
    ports:
      - "4040:4040"

    networks:
      - hadoop-net
    command: /bin/bash -c "service ssh start; tail -f /dev/null"

  master:
    build:
      context: ../
      dockerfile: docker/master.dockerfile
    image: master
    container_name: master
    hostname: master-server

    ports:
      - "9004:9004"
      - "9870:9870"

    networks:
      - hadoop-net
    command: /bin/bash -c "service ssh start; tail -f /dev/null"
    
  worker1:
    build:
      context: ../
      dockerfile: docker/worker.dockerfile
    image: worker
    container_name: worker1
    hostname: worker1-server
    ports:
      - "19004:9004"
      - "19870:9870"
    networks:
      - hadoop-net
    command: /bin/bash -c "service ssh start; tail -f /dev/null"

  worker2:
    build:
      context: ../
      dockerfile: docker/worker.dockerfile
    image: worker
    container_name: worker2
    hostname: worker2-server
    ports:
      - "29004:9004"
      - "29870:9870"
    networks:
      - hadoop-net
    command: /bin/bash -c "service ssh start; tail -f /dev/null"
