services:
  base:
    build: 
      context: ./base
      dockerfile: Dockerfile
    image: base

  client:
      build: 
        context: ./client
        dockerfile: Dockerfile
      image: client
      depends_on:
        - base
  master:
    build: 
      context: ./master
      dockerfile: Dockerfile
    image: master
    depends_on:
      - base
  
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    image: worker
    depends_on:
      - base